"""empty message

Revision ID: 14803bd6d126
Revises: 
Create Date: 2017-11-20 07:58:04.009156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14803bd6d126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squadron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircrafts',
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('t_m_s', sa.String(length=64), nullable=True),
    sa.Column('squadron_id', sa.Integer(), nullable=True),
    sa.Column('airframe_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('squadron_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('e_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenanceDues',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('type_inspection', sa.String(length=80), nullable=True),
    sa.Column('date_due', sa.String(), nullable=True),
    sa.Column('hours_due', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'aircraft_id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MaintenanceHistory',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('type_inspection', sa.String(length=80), nullable=True),
    sa.Column('aircraft_hours', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('date_complete', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'aircraft_id', 'date_complete')
    )
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('flight_date', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.aircraft_id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('MaintenanceHistory')
    op.drop_table('pilot')
    op.drop_table('mechanic')
    op.drop_table('maintenanceDues')
    op.drop_table('engines')
    op.drop_table('administrator')
    op.drop_table('user')
    op.drop_table('aircrafts')
    op.drop_table('squadron')
    # ### end Alembic commands ###
